---
title: "quiz3"
author: "Abdelrahman Elsehaily"
date: "October 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Q1

```{r}
set.seed(12)
library(AppliedPredictiveModeling)
data(segmentationOriginal)
library(caret)
training <- segmentationOriginal[segmentationOriginal$Case=="Train",]
modelFit<-train(Class ~ .,data = training,method="rpart")
```

```{r}
library("rattle")
modelFit$finalModel
fancyRpartPlot(modelFit$finalModel)
```


## Q3

```{r}
library(pgmm)
data(olive)
olive = olive[,-1]
newdata = as.data.frame(t(colMeans(olive)))
```

```{r}
mf<-train(Area ~.,data = olive,method="rpart")
predict(mf$finalModel,newdata)
fancyRpartPlot(mf$finalModel)
```

## Q4

```{r}
library(ElemStatLearn)
data(SAheart)
set.seed(8484)
train = sample(1:dim(SAheart)[1],size=dim(SAheart)[1]/2,replace=F)
trainSA = SAheart[train,]
testSA = SAheart[-train,]
set.seed(13234) 
mf4=train(chd ~ age+obesity+tobacco+alcohol+typea+ldl,data=trainSA,method="glm",family="binomial")
```

```{r}
missClass = function(values,prediction){sum(((prediction > 0.5)*1) != values)/length(values)}
missClass(trainSA$chd,predict(mf4,trainSA))
missClass(testSA$chd,predict(mf4,testSA))
          
```












